In [14]:
import sys 
sys.path.append('/home/haroldvaz/computacional/lib/python3.8/site-packages')

import numpy as np 


In [57]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = a
a = np.array([[ 2,1, 4, 1 ],[ 3, 4, -1, -1 ] , [ 1, -4, 1, 5 ] ,[ 2, -2, 1, 3 ]], float)

for i in range(0,len(a)-1):
    if a[i][i] == 0:
        a[[i,i+1]]=a[[i+1,i]]
        i = i-1
    elif a[i][i] != 0:
        a[i] = a[i]/a[i][i]
        
    for j in range(i+1,len(a)):
        a[j] = - (a[j][i]* a[i]) + a[j]
a

array([[ 1. ,  0.5,  2. ,  0.5],
       [ 0. ,  1. , -2.8, -1. ],
       [-0. , -0. ,  1. , -0. ],
       [ 0. ,  0. ,  0. , -1. ]])

In [7]:
for i in range(0,len(a)):
    print(a[i][i])

1
4


In [8]:
a[0][0]

1

In [25]:
a = np.array([[0,2,3],[1,0,6],[3,4,5]])

In [26]:
a[0+1:]= - (a[0+1][0]* a[0:]) + a[0+1:]

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

In [19]:
a

array([[3, 4, 5],
       [1, 0, 6],
       [0, 2, 3]])

In [32]:
3*a[0]

array([0, 6, 9])