In [1]:
import sys 
sys.path.append('/home/haroldvaz/computacional/lib/python3.8/site-packages')

In [2]:
import numpy as np
import matplotlib.pyplot as plt 

In [3]:
n = 10
x = np.zeros((1,n),dtype=float)
mesh, a = np.meshgrid(x,x)

In [4]:
V = 5
for i in range(n):
    for j in range(n):
        if i == 0:
            mesh[i][j] = V
        else:
            continue

In [5]:
def cuad(x1,x2,y1,y2,a,V):
    n1 = int((x1+x2)/a)
    n2 = int((y1+y2)/a)
    v = V
    x = np.zeros((1,n1),dtype=float)
    y = np.zeros((1,n2),dtype=float)
    mesh, phi = np.meshgrid(x,y)
    for i in range(n2):
        for j in range(n1):
            if i == 0:
                mesh[i][j] = v
            else:
                continue
    return mesh,phi

In [6]:
cuad(10,0,20,0,1,5)

(array([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [7]:
y = np.zeros((1,20),dtype=float)

In [8]:
y

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [9]:
me = np.meshgrid(x,y)

In [10]:
a=1
x1 = 0
x2= 10
y1 = 0
y2= 20

n1 = int((x1+x2)/a)
n2 = int((y1+y2)/a)
v = V
x = np.zeros((1,n1),dtype=float)
y = np.zeros((1,n2),dtype=float)
mesh,l = np.meshgrid(x,y)

In [11]:
for i in range(n2):
    for j in range(n1):
        print(mesh[i][j])

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0


In [12]:
mesh[10][0]

0.0

In [13]:
mesh[11][0]

0.0

In [14]:
mesh[0][10]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [15]:
mesh

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
ma,phi = cuad(10,0,20,0,0.001,10)

In [17]:
ma

array([[10., 10., 10., ..., 10., 10., 10.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [18]:
phi

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [19]:
print(np.shape(ma),np.shape(phi))

(20000, 10000) (20000, 10000)


In [20]:
# Constantes
M = 100         # Cuadros en la cuadicula
V = 1.0         # Voltaje en la parte superior de la placa
target = 1e-6   # Precision

In [23]:
phi2 = np.zeros([M+1,M+1],float)
phi2[0,:] = V
# phi2

Dphi2 = np.empty([M+1,M+1],float)
phi2


array([[1., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [32]:
# Creamos unas cajas (arreglos) para guardar los valores del potencial
phi = np.zeros([M+1,M+1],float)
phi[0,:] = V
Dphi = np.empty([M+1,M+1],float)



delta = 1.0
while delta>target:
    # Calculamos los nuevos valores del potencial
    for i in range(M+1):
        for j in range(M+1):
            if i==0 or i==M or j==0 or j==M:
                Dphi[i,j] = phi[i,j]
            else:
                Dphi[i,j] = (phi[i+1,j] + phi[i-1,j]+ phi[i,j+1] + phi[i,j-1])/4

    # Calculamos la diferencia maxima respecto de los valores anteriores
    delta = np.max(abs(phi-Dphi))
    print(delta)

    # Intercambiamos los arreglos
    phi,Dphi = Dphi,phi



0.25
0.125
0.078125
0.0546875
0.046875
0.040283203125
0.034912109375
0.030548095703125
0.0269775390625
0.024026870727539062
0.021562576293945312
0.019483327865600586
0.01826561987400055
0.01714233309030533
0.016110618598759174
0.015164853539317846
0.014298290479928255
0.01350394100882113
0.01277503510209499
0.012105244259146275
0.011488773486689752
0.010920381535242996
0.010395363192202467
0.00990951288427766
0.0095678055434405
0.009241630354459573
0.008930551632850836
0.008634029410666322
0.008351461175408192
0.008082211578689658
0.007825633433334478
0.00758108238854277
0.0073479270121942775
0.0071255555368252566
0.006913380185852802
0.006710839750720343
0.00651740091089914
0.0063325586581741145
0.006155836090969258
0.005986783774077131
0.005856636300727636
0.005730343108503733
0.0056078193249337605
0.005488972290574878
0.005373703872472824
0.005261912328497376
0.005153493805245379
0.00504834353673117
0.004946356798615437
0.004847429662643121
0.004751459587800377
0.004658345878073067
